source "https://rubygems.org"
gem "rails", "4.2.6"
gem "sqlite3"
gem "sass-rails", "~> 5.0"
gem "uglifier", ">= 1.3.0"
gem "coffee-rails", "~> 4.1.0"
gem "jquery-rails"
gem "turbolinks"
gem "jbuilder", "~> 2.0"
gem "sdoc", "~> 0.4.0", group: :doc
gem "bootstrap-sass", "3.2.0.0"
gem "country_select"
gem "carrierwave"
gem "mini_magick"
gem "fog"
gem "kaminari"
gem "faker"
gem "config"
gem "devise"
gem "cancancan"
gem "omniauth"
gem "omniauth-oauth2"
gem "omniauth-google-oauth2"
gem "omniauth-facebook"
gem "social-share-button"
gem "sidekiq"
gem "ransack"
gem "bcrypt"
gem "jquery-turbolinks"
gem "whenever"
gem "sinatra"
gem "delayed_job_active_record"
gem "daemons"
gem "public_activity"
gem "ckeditor"
gem "kaminari-bootstrap"
gem "figaro"

group :development, :test do
  gem "byebug"
  gem "web-console"
  gem "spring"
  gem "letter_opener"
  gem "rspec-rails"
  gem "capybara"
  gem "factory_girl_rails"
  gem "simplecov"
end

group :development do
  gem "spring"
end
